# This file was generated by GoReleaser. DO NOT EDIT.
cask "howtfdoi" do
  version "1.0.13"

  on_macos do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_amd64.tar.gz"
      sha256 "a41b8f5f9bf74f66c9fa1fa536d8bca5ef1042b356305c2614ca3eeb5979b079"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_arm64.tar.gz"
      sha256 "23aa8f9328ea22ca350340f9d68e70b23f01c84afd218f4f3bde99060ac323ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_amd64.tar.gz"
      sha256 "e59e476c1e95fe53ebce4cf8dbc913ecfa0beaa108bfdfcf883493d00425627d"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_arm64.tar.gz"
      sha256 "ccd34b2a118c232879a555fee6a199646e25a2614f7af63ce35e88c90e4228c1"
    end
  end

  name "howtfdoi"
  desc "Instant AI-powered CLI command answers from your terminal"
  homepage "https://github.com/NeckBeardPrince/howtfdoi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "howtfdoi"

  # No zap stanza required

  caveats <<~EOS
    howtfdoi is not notarized. If macOS Gatekeeper blocks it on first run, remove the quarantine attribute:
      xattr -d com.apple.quarantine $(which howtfdoi)
  EOS
end
