# This file was generated by GoReleaser. DO NOT EDIT.
cask "howtfdoi" do
  version "1.0.12"

  on_macos do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_amd64.tar.gz"
      sha256 "a617ca7216afada9bc1dbae1fd72b22ed7fbb7a8516b0186618331ef99cb8a3f"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_arm64.tar.gz"
      sha256 "e2e2db8364d86b85b445bb6f8c98b92ffcdf3b261fbb0f1b5ce81ca379761205"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_amd64.tar.gz"
      sha256 "3fbec030a5faf716184984ac9951ee483fa954934d5a51870a76b2d38fce982e"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_arm64.tar.gz"
      sha256 "a2a8cbd2585556309cb291ca1765a35fb1067988e4ca8232b7b4e7ba34c41bc7"
    end
  end

  name "howtfdoi"
  desc "Instant AI-powered CLI command answers from your terminal"
  homepage "https://github.com/NeckBeardPrince/howtfdoi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "howtfdoi"
  generate_completions_from_executable "howtfdoi",
    shell_parameter_format: "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    howtfdoi is not notarized. If macOS Gatekeeper blocks it on first run, remove the quarantine attribute:
      xattr -d com.apple.quarantine $(which howtfdoi)
  EOS
end
