# This file was generated by GoReleaser. DO NOT EDIT.
cask "howtfdoi" do
  version "1.0.14"

  on_macos do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_amd64.tar.gz"
      sha256 "f7d6726e0bb08a89474bfca8ad5e490308f4f0ccaba250ba3b3dfccc6d091851"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_darwin_arm64.tar.gz"
      sha256 "524a37050108fbf13090aaa15376f2c3d3a16af47910475115d56459db0aefee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_amd64.tar.gz"
      sha256 "2b1947f070c8fd3f456e503b6c6932c61340d2524a9947252c497172d29141c7"
    end
    on_arm do
      url "https://github.com/NeckBeardPrince/howtfdoi/releases/download/v#{version}/howtfdoi_#{version}_linux_arm64.tar.gz"
      sha256 "19caef56c21120404861aa637f4b521527c9150442321aa254f729c25e495d4a"
    end
  end

  name "howtfdoi"
  desc "Instant AI-powered CLI command answers from your terminal"
  homepage "https://github.com/NeckBeardPrince/howtfdoi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "howtfdoi"

  # No zap stanza required

  caveats <<~EOS
    howtfdoi is not notarized. If macOS Gatekeeper blocks it on first run, remove the quarantine attribute:
      xattr -d com.apple.quarantine $(which howtfdoi)
  EOS
end
